# Numpy 

In [82]:
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 26.1
[notice] To update, run: pip install --upgrade pip


In [83]:
!pip install matplotlib


[notice] A new release of pip is available: 25.1.1 -> 26.1
[notice] To update, run: pip install --upgrade pip


In [84]:
import numpy as np 
import matplotlib.pyplot as plt

In [85]:
#creating Numpy array 
#create manually

#1D array 
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [86]:
arr.dtype

dtype('int64')

In [87]:
arr.ndim

1

In [88]:
# 2d array
arr_2 = np.array([[1,2,3],[4,5,6]])
arr_2

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
arr_2.ndim

2

In [90]:
# 3d array 
arr_3 = np.array([[['sanjay','rahul','bikram'],[1,2,3]]])
arr_3

array([[['sanjay', 'rahul', 'bikram'],
        ['1', '2', '3']]], dtype='<U21')

In [91]:
arr_3.ndim

3

In [92]:
arr_3.dtype

dtype('<U21')

In [93]:
# using list

a = list(range(1,10))
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [94]:
arr_l = np.array(a)
arr_l

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
#using tuples
t = tuple(range(0,20,2))
t
arr_t = np.array(t)
arr_t

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [96]:
#using set 
s = set(range(1,50,5))
s

{1, 6, 11, 16, 21, 26, 31, 36, 41, 46}

In [97]:
arr_s = np.array(s)
arr_s

array({1, 36, 6, 41, 11, 46, 16, 21, 26, 31}, dtype=object)

In [98]:
# Zeros
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [99]:
#ones
o = np.ones((3,2))
o

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [100]:
#creating with full
f = np.full((2,5),13) # creating 2*5 array with all element 13
f

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [101]:
f1 = np.full((3,3),20)
f1

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [102]:
#creating array with arange()
ar = np.arange(1,10,2)
ar

array([1, 3, 5, 7, 9])

In [103]:
#crating array with linspace
a = np.linspace(1,10,100)
a

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [104]:
a1d = np.zeros(5)
a1d

array([0., 0., 0., 0., 0.])

In [105]:
#creating identity metrics or array 
i = np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [106]:
i1 = np.eye(2,2)
i1

array([[1., 0.],
       [0., 1.]])

In [107]:
# Properties of Array 
#dimensiion
a1 = np.array([1,2,3,4])
a1.ndim

1

In [108]:
a1.dtype

dtype('int64')

In [109]:
a1.shape

(4,)

In [110]:
a1.size

4

In [111]:
#creating 5* 6 array 
arr_56 = np.full((5,6),12)
arr_56

array([[12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12]])

In [112]:
l1 = list(range(0,6))
l2 = list(range(6,12))
l3 = list(range(12,18))
l4 = list(range(18,24))
l5 = list(range(24,30))

In [113]:
l5

[24, 25, 26, 27, 28, 29]

In [114]:
l2

[6, 7, 8, 9, 10, 11]

In [115]:
l3

[12, 13, 14, 15, 16, 17]

In [116]:
arr_5 = np.array((l1,l2,l3,l4,l5))
arr_5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [117]:
# operation in array
new_arr = np.array(list(range(1,10)))
new_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
#1 scaler multiplocation
new_arr*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [119]:
#sclar sum 
new_arr+4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [120]:
#Scaler power 
new_arr**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [121]:
# arithmetic operation in array 
a2_n = np.array([[1,2,3,4],[5,6,7,8]])
a2_n

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [122]:
a2_new = a2_n - 1
a2_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [123]:
a2_n + a2_new

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [124]:
a2_n - a2_new

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [125]:
a2_n /a2_new

/var/folders/gk/8p2cy2r906j11_0stbnxqlb40000gn/T/ipykernel_77023/4264303023.py:1: RuntimeWarning: divide by zero encountered in divide
  a2_n /a2_new


array([[       inf, 2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667, 1.14285714]])

In [126]:
a2_n % a2_new

/var/folders/gk/8p2cy2r906j11_0stbnxqlb40000gn/T/ipykernel_77023/2614834892.py:1: RuntimeWarning: divide by zero encountered in remainder
  a2_n % a2_new


array([[0, 0, 1, 1],
       [1, 1, 1, 1]])

In [127]:
a2_n * a2_new

array([[ 0,  2,  6, 12],
       [20, 30, 42, 56]])

In [128]:
a2_n.shape

(2, 4)

In [129]:
a2_new.shape

(2, 4)

In [130]:
a2_n.size

8

In [131]:
a2_n.ndim

2

In [132]:
a2_n.dtype

dtype('int64')

# Reshaping of array

In [133]:
a2_n

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [134]:
x = a2_n

In [135]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [136]:
x.shape

(2, 4)

In [137]:
x.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [138]:
x.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [139]:
x.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [140]:
y = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [141]:
y.shape

(3, 4)

In [142]:
y.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [143]:
y.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [144]:
y.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [145]:
y.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [146]:
y.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [147]:
# indexing in array 
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [148]:
y[1]

array([5, 6, 7, 8])

In [149]:
y[:,3]

array([ 4,  8, 12])

In [150]:
y[1,2]

np.int64(7)

In [151]:
y[1,0:3]

array([5, 6, 7])

In [152]:
y[[1,2],[3,3]] 

array([ 8, 12])

In [153]:
y[:,1]

array([ 2,  6, 10])

In [154]:
y[:,0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [155]:
y[:,1:4]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [156]:
y[0:3,1:4]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [157]:
y.max()

np.int64(12)

In [158]:
y.min()

np.int64(1)

In [159]:
np.sum(y,axis= 0) # add sum of each columns 

array([15, 18, 21, 24])

In [160]:
y + 5 # add 5 to all the element of the y 

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [161]:
np.sum(y,axis = 1) # add element of each columns 

array([10, 26, 42])

In [162]:
y[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [165]:
y[(1,2),(3,2,)]

array([ 8, 11])